[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "triehard"
version = "0.1.0"

[dependencies]
env_logger = "*"
log = "*"
quickcheck = "*"

[dev-dependencies]
rand = "0.3.14"

[profile.bench]
debug = true
[profile.release]
debug = true
